"""Add auto-incrementing id to contacts

Revision ID: 321d393649bd
Revises: 8383911f5ed4
Create Date: 2024-08-01 11:05:04.133731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '321d393649bd'
down_revision = '8383911f5ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
