"""changed contact database

Revision ID: 8383911f5ed4
Revises: 96d0bb0cc2fd
Create Date: 2024-08-01 10:39:24.098902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8383911f5ed4'
down_revision = '96d0bb0cc2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_index('name')
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
