"""Update name fields

Revision ID: 900f0c1279e3
Revises: b34afe3e8f9f
Create Date: 2024-08-01 17:53:02.427927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900f0c1279e3'
down_revision = 'b34afe3e8f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('full_name', ['full_name'], unique=True)

    # ### end Alembic commands ###
