"""changed variable name

Revision ID: 96d0bb0cc2fd
Revises: 
Create Date: 2024-07-31 20:33:40.466507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d0bb0cc2fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.drop_column('bod')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bod', sa.DATE(), nullable=True))
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
