"""Update ID fields

Revision ID: b34afe3e8f9f
Revises: bb863f88e663
Create Date: 2024-08-01 16:38:49.299001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34afe3e8f9f'
down_revision = 'bb863f88e663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    # ### end Alembic commands ###
