"""Add auto-incrementing id to contacts

Revision ID: bb863f88e663
Revises: 321d393649bd
Create Date: 2024-08-01 15:00:43.025400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb863f88e663'
down_revision = '321d393649bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('brand_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('prescription', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('quantity')
        batch_op.drop_column('prescription')
        batch_op.drop_column('brand_name')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
